name: Jail
version: 1.0
main: me.antigravity.jail.Main
api-version: '1.21'
commands:
  jail:
    description: Players are jailed.
    usage: /jail <player> <time> [reason]
    permission: jail.admin
  unjail:
    description: Release a player from jail.
    usage: /unjail <player>
    permission: jail.admin
  setjail:
    description: Set the jail center and radius.
    usage: /setjail [radius]
    permission: jail.admin
  setrelease:
    description: Set the release location.
    usage: /setrelease
    permission: jail.admin
  sethologram:
    description: Set the jail hologram location.
    usage: /sethologram
    permission: jail.admin
permissions:
  jail.admin:
    description: Allows use of jail commands.
    default: op
